### ISSUE TITLE
Gzip returning random characters on Google App Engine

### ISSUE THREAD

**Issue by EricAndrechek** [kuszaj/Flask-GzipBomb#1]
I am running a flask server on Google App Engine on python 2.7. Using this library when I make a request to that page, it gives me this as a response:

�ybY���?p����hh�2���Wey��3 3CL.��e���Buer��<��tS�f^;y�y�U��V7�c�Y��������k�210ψ�02����%@s��:;O�d��]���)��6R�ox��O�����V���9#��HwW˱v�'���wз�hG�l4�2�ʎDCޭ����K��\��|?�qG�����s��L��˒`9.�c7��!���ѓ�y���O�C����s�(��n���f%ِ�}���9j�@敠����,	w-q�)Q���I����Wo.-V���m��g��}�y�r��,�]��pD�����dU��G*�-u	�x��}E8A��v��=�|�� U����T8r��񗍷�n�%�b��qE9�Zw�Z(O܎s�=[���6{z�F4�^Z��g��v1ڙ�J��ȟ�Wm�F���9k?�}�6\�����sLd�E��)�`F��K��	�O{u�a�O,�J[� 1�F��PX]��g�ДU��adpu��;^GO�;�A���H��`�Z�r���zQ�#�S��9�&"�f$؄�I�aN�<�`[�QY�[k����E��A�mI:ǋ�yRr9�f��jdǫ�nJH�{�|"�GD�@��%�k�a�����Z��w�ٺ������Ŧ[��ɬ��+K.�G)`0: ��Pc���_�u�Q'�v�|\܄����k,���S�O��"cz��[C����HV:1�/V��BP�'�&!��l0�Ԣ�����Sf�d�������D��������S��B����Z�X.�����[�ٖ,�q�1����\�ܳw1u���Y�� � ��LI�J_�9��	�m��Mő� 9��O���j���>9��)�fc�����,i7�i�qQ&OȲ��X{�vuo� +U�(x���u��#N�a��`���!�P�@��̜���LA�@O�Y���#Gm��+�n����K����������"��uS�i��~,��v(�̓j����a:�y���Q��M�� 2�A�ߴd��m!����[���b^�(-���W�:7�u�,�L��X @�4�]ϖ�U�Nl� �Zk;��rr�V�#��U�J�����c�G[���w�G'�0<�*���fA��%�P}��[6�Wc\�����7�'�o*��/ 8p�OE&B��~'��k�^���PI�Jdi������7�

What am I doing wrong?

**Comment by kuszaj** [comment]
I believe this is an inherit issue with Google App Engine. I assume Flask instance you have mentioned is accessible under https://andrechek.com/projects/zip-bomb. Testing it with curl reveals that `Content-Encoding` header is missing:
```bash
$ curl -v -s https://andrechek.com/projects/zip-bomb 1> /dev/null
...
> GET /projects/zip-bomb HTTP/2
> Host: andrechek.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
< HTTP/2 200 
< content-type: text/html; charset=utf-8
< x-cloud-trace-context: e70f7f43f350e9cd26fb733fe80b29f7;o=1
< date: Sun, 02 Jun 2019 21:08:36 GMT
< server: Google Frontend
< content-length: 1254
< 
{ [5 bytes data]
```
Indeed, [Google App Engine docs](https://cloud.google.com/appengine/docs/standard/python/reference/request-response-headers#headers_removed) mentions:

> [...] The response may be modified before it is returned to the client. [...]

> The following headers are ignored and removed from the response:
> * Connection
> * **Content-Encoding**
> * Content-Length
> * Date
> * Keep-Alive
> * Proxy-Authenticate
> * Server
> * Trailer
> * Transfer-Encoding
> * Upgrade

Since Google App Engine intercepts and modifies response headers from send by Flask app, the desired effect is impossible since it relies on client's decompressing given content based on response headers. I believe the only solution in that case would be to use either some other app platform that passes HTTP responses from your app as they are or your own VPS/dedicated server.
